/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  x: {
    put: {
      parameters: {
        path: {
          id: number;
        };
        query: {
          hello: string;
          world: string;
        };
        body: {
          payload: {
            action: "create" | "update";
          };
        };
        header: {
          /** Cookie */
          Cookie: string;
        };
      };
      responses: {
        /** 201 response */
        201: {
          schema: {
            id: number;
          };
        };
      };
    };
  };
}

export interface definitions {}

export interface operations {}
